#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=$(getApplication)

fluentMeshToFoam elbow.msh -scale 10 > log.fluentToMesh

cp -r boundary constant/polyMesh
decomposePar > log.decompose
mpirun -np 6 reactingAlphaFoam -parallel > log.react
reconstructPar > log.reconstruct
touch open.foam

#------------------------------------------------------------------------------
